// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Property_Search_Web_App.Data;

#nullable disable

namespace Property_Search_Web_App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250821070835_seedDataToPropertyAndSpaces")]
    partial class seedDataToPropertyAndSpaces
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Property_Search_Web_App.Models.Entity.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Price")
                        .HasDatabaseName("IX_Property_Price");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Property_Type");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, City, State",
                            Description = "A beautiful family house",
                            Price = 300000m,
                            Type = "house"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak St, City, State",
                            Description = "Cozy apartment in the city center",
                            Price = 150000m,
                            Type = "apartment"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine St, City, State",
                            Description = "Modern condo with great amenities",
                            Price = 250000m,
                            Type = "condo"
                        },
                        new
                        {
                            Id = 4,
                            Address = "101 Maple Ave, City, State",
                            Description = "Spacious house with a large yard",
                            Price = 400000m,
                            Type = "house"
                        },
                        new
                        {
                            Id = 5,
                            Address = "202 Birch Rd, City, State",
                            Description = "Affordable apartment with great location",
                            Price = 120000m,
                            Type = "apartment"
                        },
                        new
                        {
                            Id = 6,
                            Address = "303 Cedar Dr, City, State",
                            Description = "Nice condo near the beach",
                            Price = 220000m,
                            Type = "condo"
                        },
                        new
                        {
                            Id = 7,
                            Address = "404 Elm St, City, State",
                            Description = "House with open-plan living space",
                            Price = 350000m,
                            Type = "house"
                        },
                        new
                        {
                            Id = 8,
                            Address = "505 Walnut Ln, City, State",
                            Description = "Bright apartment with excellent views",
                            Price = 170000m,
                            Type = "apartment"
                        },
                        new
                        {
                            Id = 9,
                            Address = "606 Ash Blvd, City, State",
                            Description = "Luxury condo with pool and gym",
                            Price = 280000m,
                            Type = "condo"
                        },
                        new
                        {
                            Id = 10,
                            Address = "707 Maple Dr, City, State",
                            Description = "Large family house with 5 bedrooms",
                            Price = 320000m,
                            Type = "house"
                        });
                });

            modelBuilder.Entity("Property_Search_Web_App.Models.Entity.Space", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("Size")
                        .HasDatabaseName("IX_Space_Size");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Space_Type");

                    b.ToTable("Spaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Master bedroom",
                            PropertyId = 1,
                            Size = 150m,
                            Type = "bedroom"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Modern kitchen",
                            PropertyId = 1,
                            Size = 100m,
                            Type = "kitchen"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Spacious living room",
                            PropertyId = 1,
                            Size = 200m,
                            Type = "living room"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cozy bedroom",
                            PropertyId = 2,
                            Size = 120m,
                            Type = "bedroom"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Full bathroom",
                            PropertyId = 2,
                            Size = 60m,
                            Type = "bathroom"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Luxury bedroom with ensuite",
                            PropertyId = 3,
                            Size = 140m,
                            Type = "bedroom"
                        },
                        new
                        {
                            Id = 7,
                            Description = "State-of-the-art kitchen",
                            PropertyId = 3,
                            Size = 110m,
                            Type = "kitchen"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Open-plan living room",
                            PropertyId = 4,
                            Size = 220m,
                            Type = "living room"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Large bedroom",
                            PropertyId = 4,
                            Size = 130m,
                            Type = "bedroom"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Compact kitchen with modern appliances",
                            PropertyId = 5,
                            Size = 90m,
                            Type = "kitchen"
                        });
                });

            modelBuilder.Entity("Property_Search_Web_App.Models.Entity.Space", b =>
                {
                    b.HasOne("Property_Search_Web_App.Models.Entity.Property", "Property")
                        .WithMany("Spaces")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Property_Search_Web_App.Models.Entity.Property", b =>
                {
                    b.Navigation("Spaces");
                });
#pragma warning restore 612, 618
        }
    }
}
